services:
  api:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - '3005:3005'
    depends_on:
      - pg
    restart: on-failure
    command: ['npm', 'run', 'start:migration']
    env_file:
      - .env.docker

  pg:
    image: postgis/postgis
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: nara
      POSTGRES_DB: nara-space
